# docker-compose.yml

version: '3.9'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vimal
      MYSQL_DATABASE: eclipse
      MYSQL_PASSWORD: vimal
      PORT: 3306

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: eclipse
      DB_USER: root
      DB_PASSWORD: vimal

volumes:
  mysql_data:
